import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Arma Türk Birlikleri</title>
        <meta name="description" content="Generated by ATB" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="ARMA TURK BIRLIKLERI" message="Generated by ATB" />

      <Slider slides={SliderData} />
      <Image
        src="/public/image/arma.png"
        alt=''
        width='40'
        height='40'
        objectFit='cover'

      />
    </div>
  )
}
