import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'


export default function Home({ heading, message }) {

  return (
    <div>
      <Head>
        <title>Arma Türk Birlikleri</title>
        <meta name="description" content="Generated by ATB" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="ARMA TURK BIRLIKLERI" message="asdasdasdasdasdasd asd asd as da sdasd asd" />



    </div>
  )
}
