import Head from 'next/head'
import Hero from '../components/Hero'
import Video from '../components/Video'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Arma Türk Birlikleri</title>
        <meta name="description" content="Generated by ATB" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero clas/>
      <Video />


    </div>
  )
}
